name: Enviar E-mail Mensal

on:
  schedule:
    - cron: '0 12 1 * *'  # Executa todo dia 1 do mês às 12:00 UTC (9:00 Brasília)
  workflow_dispatch:       # Permite execução manual no GitHub

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install pandas pdfkit openpyxl

      - name: Instalar wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Executar script de envio
        env:
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
        run: |
          python enviar_ranking.py
